### PR TITLE
Update docs

### LINKED ISSUE #146: Update docs

### PR DESCRIPTION
**Pull request by emmanuelroussel**
Closes #146 

I simply ran `npm run docs` to update them.

@AdamVig have you ever used the docs for this project? Do you think they would be useful in the future? I personally have never used them and looking at them, they don't seem useful at all right now. They simply state in text what the code is (arguments of methods and things like that) which you can understand better by simply looking at the code.

I think we should either stop using docs on the front end or try to make them actually useful with comments and everything. Do you have any preference?

### CODE REVIEW

**Comment by AdamVig** [comment]
I never have used them, no. In general, I would find them helpful for services (like Stockpile Data). Having descriptions of what each function is useful for could be helpful for other developers looking at the project.

We definitely don't need docs for components and pages, though.

**Comment by emmanuelroussel** [comment]
Good to know. Typedoc might be overkill then. Do you think comments could be enough?

**Comment by AdamVig** [comment]
Yeah, I think they should be enough. Style-wise, I would prefer:
```JavaScript
/** Description of function */
() => {}
// or:
/**
 * Multi-line
 * description of function
 */
() => {}
```

**Comment by emmanuelroussel** [comment]
Yeah I think it'd a much better solution than having a folder full unused docs haha.

**Comment by emmanuelroussel** [comment]
@AdamVig any other functions you noticed should be explained?

**Pull request merged**
